workflows:
  android-build:
    name: Android Build Cordova

    environment:
      node: 18
      java: 17

    scripts:
      - npm install -g cordova
      - npm install
      - cordova platform rm android || true
      - cordova platform add android@12
      - cordova build android

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
